project:
  type: book
  output-dir: docs

book:
  title: "Visualise cophylogenetic signals"
  subtitle: "Phylogeny x Bipartite Network Workflows"
  page-navigation: true
  search: true
  sidebar:
    style: docked
    collapse-level: 2
  chapters:
    - index.qmd
    - ggbipartite-visualization-ja.qmd
    - ggbipartite-publishable-ja.qmd
    - ggbipartite-sciname-tree-ja.qmd

bibliography: references.bib

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [litera, styles-modern.scss]
      dark: [litera, styles-modern-dark.scss]
    highlight-style: nord
    toc: true
    toc-depth: 3
    number-sections: false
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    anchor-sections: true
    link-external-newwindow: true
    grid:
      sidebar-width: 320px
      body-width: 980px
      margin-width: 240px
  pdf:
    pdf-engine: lualatex
    documentclass: bxjsbook
    classoption: lualatex, ja=standard, jafont=BIZ UDGothic
    include-in-header:
      - text: |
          \setmainfont{Times New Roman}[
            SmallCapsFont={STIX Two Text},
            SmallCapsFeatures={Letters=SmallCaps},
          ]
    monofont: Monaspace Neon Var
    urlcolor: teal
    citecolor: teal
editor: visual
